// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var App = 0;

var Main = 0;

var Pattern = 0;

exports.App = App;
exports.Main = Main;
exports.Pattern = Pattern;
/* No side effect */
