// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE

import * as ReactDOMRe from "reason-react/lib/es6/src/ReactDOMRe.js";
import * as ReasonReact from "reason-react/lib/es6/src/ReasonReact.js";
import * as Application$Getthenotes from "./components/Application/application.bs.js";

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Application$Getthenotes.make(/* array */[])), "app");

export {
  
}
/*  Not a pure module */
